led brightness argument
rhasspy/wyoming-satellite pull request #101
Opened 2024-02-08 06:07 UTC by llluis

Second try
Request #98.

2024-02-09 08:38 UTC, blacknell commented
this is great - much needed

2024-03-24 22:04 UTC, Pr0mises commented
works great thank you

2024-06-27 08:07 UTC, Aohzan commented
hello @synesthesiam , can you check this PR :pray:

2024-06-30 15:47 UTC, TN-1 commented
Working brilliantly, this is much needed in master. Can it be merged in please? Is there any work that is required?

2024-06-30 16:26 UTC, synesthesiam requested changes

2024-06-30 16:26 UTC, synesthesiam commented on examples/2mic_service.py
> +    parser.add_argument("--led-brightness", type=int, default=31, help="LED brightness (integer from 1 to 31)")
Can you add `choices=range(1, 32)` to restrict the range?

2024-06-30 16:27 UTC, synesthesiam commented
Small change requested and we're good to go 👍

2024-07-01 16:20 UTC, synesthesiam approved these changes

2024-07-01 16:20 UTC, synesthesiam commented
Merging now. Will add changes afterwards.

2024-07-01 16:20 UTC, merged

2024-11-15 02:05 UTC, huseman21 commented
I'm doing somthing wrong,  This is how I am calling Wyoming-satellite but it errors out with the --led-brightness. any help?

[Service]
Type=simple
ExecStart=/home/me/wyoming-satellite/script/run --name 'my satellite' --led-brightness 5 --uri 'tcp://0.0.0.0:10700' --mic-command 'arecord -D plughw:CA>
WorkingDirectory=/home/huseman/wyoming-satellite
Restart=always
RestartSec=8

2024-11-15 07:34 UTC, Aohzan commented
It's an other service to run, my config (from 1 year ago)

```
[Unit]
Description=Respeaker LEDs

[Service]
Type=simple
ExecStart=/home/me/wyoming-satellite/examples/.venv/bin/python3 2mic_service.py --uri 'tcp://127.0.0.1:10500' --led-brightness 3
WorkingDirectory=/home/me/wyoming-satellite/examples
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
```