Adjust compile threads for low memory boards
rhasspy/wyoming-satellite pull request #171
Opened 2024-06-08 15:44 UTC by tannisroot

When running the latest, non-legacy Raspberry PI OS Lite version, it seems that some people with Pi Zero 2W boards are unable to install the respeaker driver due to running out of memory, see https://github.com/rhasspy/wyoming-satellite/issues/170#issuecomment-2153441822
Someone adjusted swap size to workaround this, and it compiled successfully.
In my less intrusive workaround, I've changed the script to compile the dkms module with half the threads if the board has less than 512MBs of main memory. This should lower the memory requirements and avoid OOM issues.

2024-06-11 01:11 UTC, tannisroot commented
A user has reported that this did fix the driver installation issues under bookworm and pi zero w2
https://github.com/rhasspy/wyoming-satellite/issues/170#issuecomment-2159407355

2024-06-21 15:22 UTC, tannisroot commented
After this PR is merged, https://github.com/rhasspy/wyoming-satellite/pull/167 can be merged too.

2024-06-23 18:58 UTC, tannisroot commented
Force push didn't change anything but simplify how threads are set, instead of dividing by 2 it just hard sets threads to 2 if there is 512 mb or less memory and more than 2 cores (which is the case for Pi Zero 2W). In my testing it was enough to avoid OOM issue.

2024-06-23 18:59 UTC, tannisroot commented
@synesthesiam could you review and merge this? This is needed to workaround OOM issues when installing the driver on bookworm. Thanks!

2024-06-26 18:40 UTC, synesthesiam requested changes

2024-06-26 18:40 UTC, synesthesiam commented on etc/install-respeaker-drivers.sh
> +if  [ "$memory" -le 512 ] && [ "$threads" -gt 2 ]; then
```suggestion
if  [ "${memory}" -le 512 ] && [ "${threads}" -gt 2 ]; then
```

2024-06-26 18:40 UTC, synesthesiam commented
Minor change, and we'll be good. Thanks!

2024-06-26 18:44 UTC, tannisroot commented on etc/install-respeaker-drivers.sh
> +if  [ "$memory" -le 512 ] && [ "$threads" -gt 2 ]; then
Done!

2024-06-26 18:52 UTC, tannisroot commented
> Minor change, and we'll be good. Thanks!

Commited the change, can be merged now! (not sure why it's not auto-merging).

2024-07-01 14:35 UTC, synesthesiam approved these changes

2024-07-01 14:35 UTC, merged

2024-07-01 14:35 UTC, synesthesiam commented
Thanks!